---
AWSTemplateFormatVersion: '2010-09-09'
Description: Cloudformation Template to spin up Variant Spark on EMR clusters V3 (Version 5 of EMR only)
Parameters:
  NumTree:
    Description: Number of Trees
    Type: Number
    Default: 100
  TreeBatch:
    Description: Trees in batch
    Type: Number
    Default: "100"
  PhenotypeFile:
    Description: Phenotype File in S3
    Type: String
    Default: "s3://csiro-tb/share/Hipster2/Hipster.csv"
  PhenotypeColumn:
    Description: Phenotype PhenotypeColumn
    Type: String
    Default: "Hipster"
  InputFile:
    Type: String
    Default: "s3://csiro-tb/share/Hipster2/VCF/Small.558938.vcf.bz2"
  OutputFile:
    Type: String
    Default: "s3://csiro-tb/share/Hipster2/test-maciej1.out"
  clusterName:
    Description: Name of the cluster
    Type: String
  taskInstanceCount:
    Description: Number of task instances
    Type: String
  emrVersion:
    Description: Version of EMR
    Type: String
    Default: "emr-5.12.0"
    ConstraintDescription: 'Must be EMR Version 5 (i.e: emr-5.3.0)'
  masterInstanceType:
    Description: Instance type of Master Node
    Type: String
    Default: "m4.large"
    AllowedValues: 
      - m4.large
  coreInstanceType:
    Description: Instance type of Core Node
    Type: String
    Default: "m4.large"
    AllowedValues:
      - m4.large
  taskInstanceType:
    Description: Instance type of Task Node
    Type: String
    Default: "m4.large"
    AllowedValues: 
      - m4.large
  environmentType:
    Description: What environment do you want the cluster to be in
    Type: String
    Default: "live"
  s3BucketBasePath:
    Description: Bucket to log EMR actions to
    Type: String
  taskBidPrice:
    Description: Bid price for Task nodes
    Type: String
    Default: "OnDemandPrice"
  terminationProtected:
    Description: Is the cluster to have termination protection enabled
    Type: String
    AllowedValues:
    - 'true'
    - 'false'
    Default: 'false'
    ConstraintDescription: Boolean
  awsRegion:
    Description: awsRegion
    Default: ap-southeast-2
    AllowedValues:
    - ap-southeast-2
    Type: String
Conditions:
  isLive:
    Fn::Equals:
    - Ref: environmentType
    - live
Resources:
  EMRClusterV5:
    Type: AWS::EMR::Cluster
    Properties:
      Instances:
        MasterInstanceGroup:
          InstanceCount: 1
          InstanceType:
            Ref: masterInstanceType
          Market: ON_DEMAND
          Name: Master instance group - 1
        CoreInstanceGroup:
          InstanceCount: 1
          InstanceType:
            Ref: coreInstanceType
          Market: ON_DEMAND
          Name: Core instance group - 2
        TerminationProtected:
          Ref: terminationProtected
      BootstrapActions:
      - Name: Install Jupyter
        ScriptBootstrapAction:
          Path: "s3://csiro-tb/lib/jupyter/bootstrap/install-jupyter.sh"
      - Name: Install Hail
        ScriptBootstrapAction:
          Args:
            - "--input-path"
            - "s3://csiro-tb/lib/hail/0.1_2.2.1"
            - "--hail-version"
            - "0.1"
            - "--spark-version"
            - "2.2.1"
          Path: "s3://csiro-tb/lib/jupyter/bootstrap/install-hail.sh"
      Configurations:
      - Classification: emrfs-site
        ConfigurationProperties:
          fs.s3.maxConnections: 500
      - Classification: spark
        ConfigurationProperties:
          maximizeResourceAllocation: 'true'
      - Classification: spark-defaults
        ConfigurationProperties:
          spark.sql.files.openCostInBytes: '1099511627776'
          spark.hadoop.io.compression.codecs: 'org.apache.hadoop.io.compress.DefaultCodec,is.hail.io.compress.BGzipCodec,org.apache.hadoop.io.compress.GzipCodec'
          spark.hadoop.parquet.block.size: '1099511627776'
          spark.executor.extraClassPath: '/usr/lib/hadoop-lzo/lib/*:/usr/lib/hadoop/hadoop-aws.jar:/usr/share/aws/aws-java-sdk/*:/usr/share/aws/emr/emrfs/conf:/usr/share/aws/emr/emrfs/lib/*:/usr/share/aws/emr/emrfs/auxlib/*:/usr/share/aws/emr/security/conf:/usr/share/aws/emr/security/lib/*:/home/hadoop/hail-all-spark.jar'
          spark.locality.wait: '10s'
          spark.driver.extraClassPath: '/usr/lib/hadoop-lzo/lib/*:/usr/lib/hadoop/hadoop-aws.jar:/usr/share/aws/aws-java-sdk/*:/usr/share/aws/emr/emrfs/conf:/usr/share/aws/emr/emrfs/lib/*:/usr/share/aws/emr/emrfs/auxlib/*:/usr/share/aws/emr/security/conf:/usr/share/aws/emr/security/lib/*:/home/hadoop/hail-all-spark.jar'
          spark.serializer: 'org.apache.spark.serializer.KryoSerializer'
          spark.sql.files.maxPartitionBytes: '1099511627776'
          spark.dynamicAllocation.enabled: 'false'
      Applications:
      - Name: Ganglia
      - Name: Spark
      Name:
        Ref: clusterName
      JobFlowRole: "EMR_EC2_DefaultRole"
      ServiceRole: "EMR_DefaultRole"
      ReleaseLabel:
        Ref: emrVersion
      LogUri:
        Ref: s3BucketBasePath
      VisibleToAllUsers: true
      Steps:
      - Name: "VariantSpark Job"
        ActionOnFailure: "CANCEL_AND_WAIT"
        HadoopJarStep: 
          Args:
          - "spark-submit"
          - "--deploy-mode"
          - "client"
          - "--class"
          - "au.csiro.variantspark.cli.VariantSparkApp"
          - "/home/hadoop/miniconda2/envs/jupyter/lib/python2.7/site-packages/varspark/jars/variant-spark_2.11-0.2.0-a1-all.jar"
          - "importance"
          - "-ff"
          - Ref: PhenotypeFile
          - "-fc"
          - Ref: PhenotypeColumn
          - "-if"
          - Ref: InputFile
          - "-of"
          - Ref: OutputFile
          - "-rn"
          - Ref: NumTree
          - "-rbs"
          - Ref: TreeBatch
          - "-on"
          - "10000"
          - "-rmtf"
          - "0.1"
          Jar: "command-runner.jar"
      Tags:
      - Key: Name
        Value:
          Fn::Join:
          - ''
          - - emr-instance-
            - Ref: AWS::StackName
            - ''
      - Key: Environment
        Value:
          Ref: environmentType
      - Key: Stack ID
        Value:
          Ref: AWS::StackName
  EMRTaskNodes:
    Type: AWS::EMR::InstanceGroupConfig
    Properties:
      InstanceCount:
        Ref: taskInstanceCount
      InstanceType:
        Ref: taskInstanceType
      BidPrice:
        Ref: taskBidPrice
      Market: SPOT
      InstanceRole: TASK
      Name: Task instance group - 3
      JobFlowId:
        Ref: EMRClusterV5
Outputs:
  ClusterID:
    Description: "EMR Cluster ID"
    Value: !Ref EMRClusterV5